### ISSUE TITLE
generate screenshot of customized pie chart 

### ISSUE THREAD

**Issue by AirLoren** [Boavizta/boavizta-front#12]
Several options :
1) Add a Download button to generate jpg/png image of pie chart DIV and allow user to save it
2) Add a Save button to generate jpg/png image of pie chart DIV and add it at the bottom of the page (similar to https://codepedia.info/editor-example?id=35)

**Comment by youenchene** [comment]
https://github.com/gliffy/canvas2svg

**Comment by ip512** [comment]
fixed by #20
