### ISSUE TITLE
Export selected data as CSV

### ISSUE THREAD

**Issue by da-ekchajzer** [Boavizta/boavizta-front#14]
## Problem

I want to export my selection with the modification I have made (duration and location) as a CSV.

## Field

Export all the field of the original CSV plus :

* Scope2 (measured with user custom value)
* Scope3
* used location 
* used life duration

**Comment by odelcroi** [comment]
Is it 2 csv files? one for the filtered datagrid and another with the result values?

**Comment by da-ekchajzer** [comment]
I thought it could be only one CSV with the original fields + the measured field (scope2 and Scope3) + the configuration field (location, life duration) for each selected line.
