### ISSUE TITLE
yearly value is wrong with lifetime = 0

### ISSUE THREAD

**Issue by odelcroi** [Boavizta/boavizta-front#38]
Steps to reproduce : 
- set lifetime value to 0
- set annually to true

<img width="865" alt="image" src="https://user-images.githubusercontent.com/4077729/173031213-ff3fada9-d5a6-4cbb-9afa-7f20cdc930fe.png">

**Comment by AirLoren** [comment]
This bug is fixed with [b5780d9](https://github.com/Boavizta/boavizta-front/commit/b5780d92e4287ccf2eaab6bef4cf8b3bc00c7999) because lifetime could not be set to 0 anymore.
