### ISSUE TITLE
export csv does not take into account yearly param

### ISSUE THREAD

**Issue by odelcroi** [Boavizta/boavizta-front#40]
## Steps to reproduce
- switch on yearly param
- export csv
- values in csv are not yearly

**Comment by AirLoren** [comment]
I think we should provide both total and yearly impacts on CSV file

**Comment by AirLoren** [comment]
fixed with [0a8591a](https://github.com/Boavizta/boavizta-front/commit/0a8591aafa7e686e26e2b52fd3cd482c032333ae)
